// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/26/2026, 11:46:34 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["D:/Projects/Mobile Backend APPS/OtterBackendFrontend/otter-ui/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Projects/Mobile Backend APPS/OtterBackendFrontend/otter-ui/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Projects/Mobile Backend APPS/OtterBackendFrontend/otter-ui/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Projects/Mobile Backend APPS/OtterBackendFrontend/otter-ui/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Projects/Mobile Backend APPS/OtterBackendFrontend/otter-ui/plugins/**/*.{js,ts,mjs}","D:/Projects/Mobile Backend APPS/OtterBackendFrontend/otter-ui/composables/**/*.{js,ts,mjs}","D:/Projects/Mobile Backend APPS/OtterBackendFrontend/otter-ui/utils/**/*.{js,ts,mjs}","D:/Projects/Mobile Backend APPS/OtterBackendFrontend/otter-ui/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Projects/Mobile Backend APPS/OtterBackendFrontend/otter-ui/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/Projects/Mobile Backend APPS/OtterBackendFrontend/otter-ui/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/Projects/Mobile Backend APPS/OtterBackendFrontend/otter-ui/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;