// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/25/2026, 1:30:02 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/nodirbek/Desktop/otter/otter-app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/nodirbek/Desktop/otter/otter-app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/nodirbek/Desktop/otter/otter-app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/nodirbek/Desktop/otter/otter-app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/nodirbek/Desktop/otter/otter-app/plugins/**/*.{js,ts,mjs}","/Users/nodirbek/Desktop/otter/otter-app/composables/**/*.{js,ts,mjs}","/Users/nodirbek/Desktop/otter/otter-app/utils/**/*.{js,ts,mjs}","/Users/nodirbek/Desktop/otter/otter-app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/nodirbek/Desktop/otter/otter-app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/nodirbek/Desktop/otter/otter-app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/nodirbek/Desktop/otter/otter-app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;