export { useScriptTriggerConsent, useScriptEventPage, useScriptTriggerElement, useScript, useScriptGoogleAnalytics, useScriptPlausibleAnalytics, useScriptCrisp, useScriptClarity, useScriptCloudflareWebAnalytics, useScriptFathomAnalytics, useScriptMatomoAnalytics, useScriptGoogleTagManager, useScriptGoogleAdsense, useScriptSegment, useScriptMetaPixel, useScriptXPixel, useScriptIntercom, useScriptHotjar, useScriptStripe, useScriptLemonSqueezy, useScriptVimeoPlayer, useScriptYouTubePlayer, useScriptGoogleMaps, useScriptNpm, useScriptUmamiAnalytics, useScriptSnapchatPixel, useScriptRybbitAnalytics, useScriptDatabuddyAnalytics, useScriptRedditPixel, useScriptPayPal } from '#app/composables/script-stubs';
export { isVue2, isVue3 } from 'vue-demi';
export { defineNuxtLink } from '#app/components/nuxt-link';
export { useNuxtApp, tryUseNuxtApp, defineNuxtPlugin, definePayloadPlugin, useRuntimeConfig, defineAppConfig } from '#app/nuxt';
export { useAppConfig, updateAppConfig } from '#app/config';
export { defineNuxtComponent } from '#app/composables/component';
export { useAsyncData, useLazyAsyncData, useNuxtData, refreshNuxtData, clearNuxtData } from '#app/composables/asyncData';
export { useHydration } from '#app/composables/hydrate';
export { callOnce } from '#app/composables/once';
export { useState, clearNuxtState } from '#app/composables/state';
export { clearError, createError, isNuxtError, showError, useError } from '#app/composables/error';
export { useFetch, useLazyFetch } from '#app/composables/fetch';
export { useCookie, refreshCookie } from '#app/composables/cookie';
export { onPrehydrate, prerenderRoutes, useRequestHeader, useRequestHeaders, useResponseHeader, useRequestEvent, useRequestFetch, setResponseStatus } from '#app/composables/ssr';
export { onNuxtReady } from '#app/composables/ready';
export { preloadComponents, prefetchComponents, preloadRouteComponents } from '#app/composables/preload';
export { abortNavigation, addRouteMiddleware, defineNuxtRouteMiddleware, setPageLayout, navigateTo, useRoute, useRouter } from '#app/composables/router';
export { isPrerendered, loadPayload, preloadPayload, definePayloadReducer, definePayloadReviver } from '#app/composables/payload';
export { useLoadingIndicator } from '#app/composables/loading-indicator';
export { getAppManifest, getRouteRules } from '#app/composables/manifest';
export { reloadNuxtApp } from '#app/composables/chunk';
export { useRequestURL } from '#app/composables/url';
export { usePreviewMode } from '#app/composables/preview';
export { useRouteAnnouncer } from '#app/composables/route-announcer';
export { useRuntimeHook } from '#app/composables/runtime-hook';
export { useHead, useHeadSafe, useServerHeadSafe, useServerHead, useSeoMeta, useServerSeoMeta, injectHead } from '#app/composables/head';
export { onBeforeRouteLeave, onBeforeRouteUpdate, useLink } from 'vue-router';
export { withCtx, withDirectives, withKeys, withMemo, withModifiers, withScopeId, onActivated, onBeforeMount, onBeforeUnmount, onBeforeUpdate, onDeactivated, onErrorCaptured, onMounted, onRenderTracked, onRenderTriggered, onServerPrefetch, onUnmounted, onUpdated, computed, customRef, isProxy, isReactive, isReadonly, isRef, markRaw, proxyRefs, reactive, readonly, ref, shallowReactive, shallowReadonly, shallowRef, toRaw, toRef, toRefs, triggerRef, unref, watch, watchEffect, watchPostEffect, watchSyncEffect, onWatcherCleanup, isShallow, effect, effectScope, getCurrentScope, onScopeDispose, defineComponent, defineAsyncComponent, resolveComponent, getCurrentInstance, h, inject, hasInjectionContext, nextTick, provide, toValue, useModel, useAttrs, useCssModule, useCssVars, useSlots, useTransitionState, useId, useTemplateRef, useShadowRoot, Component, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue';
export { requestIdleCallback, cancelIdleCallback } from '#app/compat/idle-callback';
export { setInterval } from '#app/compat/interval';
export { computedAsync, asyncComputed, computedEager, eagerComputed, computedInject, computedWithControl, controlledComputed, createEventHook, createGlobalState, createInjectionState, createReusableTemplate, createSharedComposable, createTemplatePromise, createUnrefFn, extendRef, injectLocal, isDefined, makeDestructurable, onClickOutside, onKeyStroke, onLongPress, onStartTyping, provideLocal, reactify, createReactiveFn, reactifyObject, reactiveComputed, reactiveOmit, reactivePick, refAutoReset, autoResetRef, refDebounced, useDebounce, debouncedRef, refDefault, refThrottled, useThrottle, throttledRef, refWithControl, controlledRef, syncRef, syncRefs, templateRef, toReactive, resolveRef, resolveUnref, tryOnBeforeMount, tryOnBeforeUnmount, tryOnMounted, tryOnScopeDispose, tryOnUnmounted, unrefElement, until, useActiveElement, useAnimate, useArrayDifference, useArrayEvery, useArrayFilter, useArrayFind, useArrayFindIndex, useArrayFindLast, useArrayIncludes, useArrayJoin, useArrayMap, useArrayReduce, useArraySome, useArrayUnique, useAsyncQueue, useAsyncState, useBase64, useBattery, useBluetooth, useBreakpoints, useBroadcastChannel, useBrowserLocation, useCached, useClipboard, useClipboardItems, useCloned, useColorMode, useConfirmDialog, useCounter, useCssVar, useCurrentElement, useCycleList, useDark, useDateFormat, useDebouncedRefHistory, useDebounceFn, useDeviceMotion, useDeviceOrientation, useDevicePixelRatio, useDevicesList, useDisplayMedia, useDocumentVisibility, useDraggable, useDropZone, useElementBounding, useElementByPoint, useElementHover, useElementSize, useElementVisibility, useEventBus, useEventListener, useEventSource, useEyeDropper, useFavicon, useFileDialog, useFileSystemAccess, useFocus, useFocusWithin, useFps, useFullscreen, useGamepad, useGeolocation, useIdle, useInfiniteScroll, useIntersectionObserver, useInterval, useIntervalFn, useKeyModifier, useLastChanged, useLocalStorage, useMagicKeys, useManualRefHistory, useMediaControls, useMediaQuery, useMemoize, useMemory, useMounted, useMouse, useMouseInElement, useMousePressed, useMutationObserver, useNavigatorLanguage, useNetwork, useNow, useObjectUrl, useOffsetPagination, useOnline, usePageLeave, useParallax, useParentElement, usePerformanceObserver, usePermission, usePointer, usePointerLock, usePointerSwipe, usePreferredColorScheme, usePreferredContrast, usePreferredDark, usePreferredLanguages, usePreferredReducedMotion, usePrevious, useRafFn, useRefHistory, useResizeObserver, useScreenOrientation, useScreenSafeArea, useScriptTag, useScroll, useScrollLock, useSessionStorage, useShare, useSorted, useSpeechRecognition, useSpeechSynthesis, useStepper, useStorageAsync, useStyleTag, useSupported, useSwipe, useTemplateRefsList, useTextareaAutosize, useTextDirection, useTextSelection, useThrottledRefHistory, useThrottleFn, useTimeAgo, useTimeout, useTimeoutFn, useTimeoutPoll, useTimestamp, useToggle, useToNumber, useToString, useTransition, useUrlSearchParams, useUserMedia, useVibrate, useVirtualList, useVModel, useVModels, useWakeLock, useWebNotification, useWebSocket, useWebWorker, useWebWorkerFn, useWindowFocus, useWindowScroll, useWindowSize, watchArray, watchAtMost, watchDebounced, debouncedWatch, watchDeep, watchIgnorable, ignorableWatch, watchImmediate, watchOnce, watchPausable, pausableWatch, watchThrottled, throttledWatch, watchTriggerable, watchWithFilter, whenever } from '@vueuse/core';
export { definePageMeta } from '../node_modules/nuxt/dist/pages/runtime/composables';
export { defineLazyHydrationComponent } from '#app/composables/lazy-hydration';
export { useAppDownloads } from '../composables/useAppDownloads';
export { useAppShare } from '../composables/useAppShare';
export { useAppToast, AppToastType } from '../composables/useAppToast';
export { useFirebaseAuth } from '../composables/useFirebaseAuth.client';
export { useTaskReminderToast, TaskReminderToastState } from '../composables/useTaskReminderToast';
export { isDefaultDurationEnd, useTaskTimeSync } from '../composables/useTaskTimeSync';
export { resolveApiBaseUrl, api, getApiFieldError, getApiErrorMessage, apiGet, apiPost, apiPut, apiPatch, apiDelete } from '../utils/api';
export { resolveAppDistributionBaseUrl, fetchWindowsDownloadInfo, fetchMobileStoreLinks, WindowsDownloadInfo, MobileStoreLinks } from '../utils/app-download';
export { ACCESS_TOKEN_KEY, REFRESH_TOKEN_KEY, FIREBASE_ID_TOKEN_STORAGE_KEY, onAuthTokensChanged, migrateLegacyTokens, getAccessToken, getRefreshToken, setAuthTokens, clearAuthSession, readRememberedLogin, writeRememberedLogin, clearRememberedLogin, AuthTokens } from '../utils/auth-session';
export { buildMonthCells, buildYearMonthCells, buildYearMonths, CalendarMonthCell, CalendarYearDayCell, CalendarYearMonth } from '../utils/calendar-grid';
export { deliverSupportEmail } from '../utils/contact-email';
export { validateEmail } from '../utils/email-policy';
export { registerWebFcmDevice, enableWebPushNotifications, unregisterWebFcmDevice, WebPushRegisterResult } from '../utils/fcm-devices';
export { STATIC_LEGAL_DOCUMENTS, getStaticLegalDocument, formatLegalUpdatedAt, LegalSlug, StaticLegalDocument } from '../utils/legal-static';
export { resolveMediaUrl } from '../utils/media';
export { APP_NAV_CATALOG, SIDEBAR_NAV_IDS, BOTTOM_NAV_IDS, resolveActiveNavId, isNavItemActive, buildNavOrderMap, orderNavItems, AppNavItemId, AppNavItem } from '../utils/nav-items';
export { setAppNotificationsEnabled, NotificationPreferenceResult } from '../utils/notification-preference';
export { resolveNotificationsWsUrl, parseNotificationsWsMessage, taskIdFromNotification, NotificationsWsEvent } from '../utils/notifications-ws';
export { intervalsOverlapHalfOpen, assignTimelineOverlapLayout, timelineTaskHorizontalStyle } from '../utils/overlap-layout';
export { PASSWORD_MIN_LENGTH, PASSWORD_MAX_LENGTH, validateNewPassword } from '../utils/password-policy';
export { stopEffectAudio, stopBackgroundAudio, pauseBackgroundAudio, playBackgroundLoop, playSoundOnce } from '../utils/pomodoro-audio';
export { isPurchaseableTariff, sanitizeTariffDescription, normalizeTariffForDisplay, normalizeTariffsForDisplay } from '../utils/premium-tariffs';
export { PRIORITY_COLORS, priorityColor } from '../utils/priority-colors';
export { taskOccursOnDate, computeNextOccurrenceDate, isRecurringTask, expandTasksForDate, expandTasksForRange, resolveRealTaskId } from '../utils/recurrence';
export { saveRepeatWeekdays, loadRepeatWeekdays, persistTaskRepeatWeekdays, enrichTaskWithStoredRepeat, resolveTaskWeekdays } from '../utils/repeat-weekdays';
export { getAppSharePayload, canUseNativeShare, buildShareMessage, SHARE_NETWORKS, copyTextToClipboard, openShareUrl, AppSharePayload, ShareNetworkId, ShareNetwork } from '../utils/share-app';
export { BRAND_NAME, APP_PUBLIC_URL, APP_SHARE, SITE_LEGAL_INFO, DESKTOP_APP, PREMIUM_LANDING, PREMIUM_SUBSCRIPTION } from '../utils/site-info';
export { OTTER_TASKS_EXPORT_VERSION, tasksToExportPayload, parseTasksExport, downloadTasksExportJson, OtterTasksExportPayload, OtterExportedTask } from '../utils/task-export';
export { preferClientSchedule, apiTaskToUi, uiTaskToApiPayload, dataUrlToFile, uiTaskToFormData, groupKeyToUi, apiMatrixBlockToUi } from '../utils/task-mapper';
export { parseApiWallClock, parseTimeToMinutes, formatMinutesToTime, addMinutesToTime, defaultDurationEnd, DURATION_END_AFTER_START_MESSAGE, REPEAT_INTERVAL_MAX, REPEAT_INTERVAL_MAX_MESSAGE, validateDurationFields, validateRepeatInterval, getTaskScheduleStart, getTaskDurationMinutes } from '../utils/time';
export { useAuthStore } from '../stores/auth';
export { useCalendarStore, CalendarViewType } from '../stores/calendar';
export { useMobileApiStore } from '../stores/mobile-api';
export { useNotificationsStore } from '../stores/notifications';
export { usePomodoroStore } from '../stores/pomodoro';
export { usePremiumStore } from '../stores/premium';
export { useSettingsStore, HelpFaqItem } from '../stores/settings';
export { useSoundsStore } from '../stores/sounds';
export { useTasksStore } from '../stores/tasks';
export { defineStore, acceptHMRUpdate, usePinia, storeToRefs } from '../node_modules/@pinia/nuxt/dist/runtime/composables';